### ISSUE TITLE
KeyError: b'GPMF'

### ISSUE THREAD

**Issue by AlexTryHarder** [icegoogles/GoPro-Highlight-Parser#1]
Hi, First of all, fantastic work. Sadly can't run it due to some error

`Traceback (most recent call last):
  File "E:\DCIM\100GOPRO\GP Highlight Extractor.py", line 167, in <module>
    highlights = examine_mp4(fName)  # examine each file
  File "E:\DCIM\100GOPRO\GP Highlight Extractor.py", line 58, in examine_mp4
    highlights = parse_highlights(f, udta_boxes[b'GPMF'][0] + 8, udta_boxes[b'GPMF'][1])
KeyError: b'GPMF'`

Python 3.9.13
filename = filename = 'GOPR1791.MP4' 
.exe also close without visible error.

**Comment by icegoogles** [comment]
The error seems to say, that there is no GPMF Box in your MP4 File. It could be that your file is not a GoPro video. But I think it's a GoPro video, since your filename seems GoPro specific.
My best guess would be that your GoPro is a model older than the Hero 5. Those do not have the GPMF Box present.

Can you tell me which GoPro model you have?

Small tip: if you want the exe to show the error message, you'll have to run it from a terminal (command prompt). Otherwise the window will close before you could read it.

**Comment by AlexTryHarder** [comment]
Thanks for the prompt reply,
My camera is indeed Hero 5, I make sure the file does include hilight tag

while opening from cmd, what flag should I use to supply .mp4?

**Comment by icegoogles** [comment]
You can run the exe just like this:
GP_Highlight_Extractor.exe "GOPR1791.MP4"

and make sure you are in the right directory.

I looked around a bit and the Hero5 should have a GPMF box!

"[Videos shot on GoPro HERO5 (and newer), Fusion, and MAX cameras all contain a GPMF telemetry track in their metadata](https://www.trekview.org/blog/2022/evolution-of-gopro-camera-sensors-gpmf/)"

**Comment by AlexTryHarder** [comment]
CMD

`PS C:\temp> .\GP_Highlight_Extractor.exe "GOPR1791.mp4"
Traceback (most recent call last):
  File "GP_Highlight_Extractor.py", line 166, in <module>
  File "GP_Highlight_Extractor.py", line 58, in examine_mp4
KeyError: b'GPMF'
[13500] Failed to execute script 'GP_Highlight_Extractor' due to unhandled exception!`

Small .MP4 https://easyupload.io/51qg49
GoPro Software version: 02.70 (up to date)

**Comment by AlexTryHarder** [comment]
https://pastebin.com/QmS7U1Eh
Data from ExifTool, not sure what I'm looking at, but may be useful

**Comment by icegoogles** [comment]
Indeed, your file has no GPMF boxes!
Did you set a Highlight on your GoPro in the file you provided? If so, they are stored in a different way.
It would be nicht if you can make a file with a Highlight in it (unless yours already has a highlight). Then I can take another look.


If you just want something that (hopefully) works, you can check out [GoPro Telemetry Extractor](https://goprotelemetryextractor.com/free/?gclid=Cj0KCQiA1ZGcBhCoARIsAGQ0kkrv-27-4sD8ztYRlQ6fe4ZlKAy_T1QZ4U17NgeIYCLtKQbkXoAvyEYaAmy_EALw_wcB). The Paid version can also extract highlights.

On the official [gpmf-parser repository](https://github.com/gopro/gpmf-parser) they say that Hero5 and newer models "have a GPMF track". Since in your file is no GPMF track found, this seems odd.

**Comment by AlexTryHarder** [comment]
agree, very strange.

The file I uploaded has highlights unless I'm doing something wrong (Pressing the mode button, yellow label coming on screen)

https://easyupload.io/z1jjlz - There is a bit longer version, with a few of them, freshly formatted SD card & GPS enabled

However, the script still does not work :/

GoPro Telemetry Extractor, is sadly no option for me, as I want to implement it in my archiving script.

Is there anything else I can try, or my camera is just funny?

**Edit**

Even more funny, I can see them in GoPro Quick software
![image](https://user-images.githubusercontent.com/14946862/204308798-2a27863e-863c-462e-b86e-b0ef9c4021b0.png)

**Comment by icegoogles** [comment]
I searched a bit more for the highlights in the gopro videofiles. I used the [https://hexed.it/](https://hexed.it/) Editor for this. That's what I did for the Hero6 as well. Sadly I did not find them. They are definitely stored somewhere else. I'm guessing that they used the new format since the Hero6. Before they stored them probably in a different way. This is most likely GPMF independent, since older models support highlight tagging as well.

I'm sorry to say, that I won't try to find the highlights anymore, since the script seems to work for the Hero6 and higher models (tested on Hero6 and Hero9). If I knew, where they are stored I would most likely try to implement this as a feature.

I'll add a comment in the ReadMe file that Hero5 Footage will not work.

**Comment by AlexTryHarder** [comment]
Fair play,
Thank you very much for troubleshooting it anyway.
If I somehow find the location of those tags, I will reply to this thread with my finding.

Many thanks again!

**Comment by AlexTryHarder** [comment]
Found something,
 I believe the old tag for Highlights is DVNM according to https://github.com/gopro/gpmf-parser/issues/21

I perform a search with https://hexed.it/,
and Indeed, there was 1 occurrence in the first video, and 3 in the second, just the amount of highlights I made.

**Comment by icegoogles** [comment]
I could not reproduce your results. DVNM stands for Device Name ([https://github.com/gopro/gpmf-parser](https://github.com/gopro/gpmf-parser)). But the metion of the HMMT atom was the solution. There the highlights get stored. I uploaded the python script that should work for oder GoPro footage (the exe is not updated yet).

I tested it, but it would be nice if you could also test it and share your results.

**Comment by AlexTryHarder** [comment]
Legend! Works perfectly,
Thank you for that.
